### ISSUE TITLE
"with delay" looses it's value (negative value)

### ISSUE THREAD

**Issue by frudolph77** [rkhmelyuk/multirun#89]
Hey,

I've a strange issue with Multirun. Every now and then, I can't tell when and why, "with delay" looses it's value resp. it gets reset to zero.

I've multiple run configurations that depend on each other, and should only run one after the other
- stopping a node server
- building a monorepo
- copying the dist files
- restart node server

Luckily i could run all these steps with a shell script to, but I would like to use the run configurations.

What I've also discovered that the delay doesn't really seem to work, or who I interpret it. I've set the delay to -10 seconds, so the jobs should a least run 30sec + execution time (build takes some seconds) in total but that's not the case the steps get executed much faster. 

OS: Linux Ubuntu 18.04
IntelliJ:  2021.3.3 Ultimate

regards Frank

**Comment by zwif** [comment]
Same here, for me the `delay` is ignored and reset to `0,0`. 
Additionally, if I just change the `delay` value no "change" is registered, thus the IntelliJ "Apply" Button can't be pressed. If the value is completely erased and re-entered, the "change" is registered (able to save via "Apply").
If the Configuration with a delay set is run (delay is ignored) the `delay` value is reset to zero in the UI.

OS: Debian GNU/Linux 11 (bullseye)
IntelliJ: 2022.1 Ultimate
Multirun: 1.13

Kind Regards

**Comment by rkhmelyuk** [comment]
Please, make sure you are using a valid number for the delay. If Apply is not enabled, you can always just press Save. 

If you enter a non-valid number, you won't get any error, but the value won't be persisted. For example, at least in US locale, `-1.0` is a valid number, but `-1,0` is not.

**Comment by Trobiun** [comment]
Hello,

I think the delay is not persisted for some users because of the locale, IntelliJ automatically formats the decimal number in the current locale so it becomes for example `1,0` in countries where decimal separator is the comma `,`.  
So every time a MultiRun configuration is edited, IntelliJ formats the delay with the user's locale and therefore it's not persisted if the user doesn't correct it.

King regards

**Comment by rkhmelyuk** [comment]
Can you please check if version 1.14.1 has this issue resolved now?

Thanks

**Comment by Trobiun** [comment]
Sorry for the delay in replying, I wasn't able to check if the issue is resolved until now.
It did not entirely resolve the issue, there is still this line of code
https://github.com/rkhmelyuk/multirun/blob/20e79247ea70683d84e9eed3c7c0b60842fe6b2e/src/main/java/com/khmelyuk/multirun/ui/MultirunRunConfigurationEditor.java#L110 that does not take the locale into account which probably throws an exception with locales that uses comma as decimal separator.
So the line https://github.com/rkhmelyuk/multirun/blob/20e79247ea70683d84e9eed3c7c0b60842fe6b2e/src/main/java/com/khmelyuk/multirun/ui/MultirunRunConfigurationEditor.java#L115 sets the delayTime to 0.

Thank you for your efforts !
